### ISSUE TITLE
Container doesn't build

### ISSUE THREAD

**Issue by gcbirzan** [sjoerdmulder/teamcity-agent-docker#10] opened 2016-04-26 08:26 UTC
The get.docker.com link is invalid, it seems the correct one is: https://get.docker.com/builds/Linux/x86_64/docker-1.11.0.tgz.

**Comment by sjoerdmulder** [comment] 2016-04-26 10:17
Yes i noticed :) The problem is that docker is now split into multiple files and i didn't have time to look into this...

Reverting back to 1.10 will work though

**Comment by sjoerdmulder** [comment] 2016-05-07 22:12
This is fixed now

**Closed as completed by sjoerdmulder** 2016-05-07 22:12 UTC
